### ISSUE TITLE
script.send_gcode missing

### ISSUE THREAD

**Issue by mwelker79** [dbuezas/esp3d-homeassistant#2]
Hello,
First of all thanks for the nice integration.
I noticed that the script.send_gcode yaml is not present in the HACS package.
Would it be possible to integrate the file in the HACS repository?

**Comment by dbuezas** [comment]
Thank you!
Let me know if you have any useful feature ideas.


You can use the `esp3d.send_gcode` action directly. But to send from the dashboard, the [script helper](http://homeassistant.local:8123/config/script/dashboard) is just this:

```yaml
alias: send gcode
sequence:
  - target:
      device_id: 5b5929effa7b6fcff77688017dee3d24 # <---- change this to your id
    data:
      gcode: |
        {{ states("input_text.gcode_to_send") }}
    action: esp3d.send_gcode
mode: single
icon: mdi:printer-3d
```
